id: default_hmw_s
name: Default HMW S
description: Default wafer, west half-moon, southern structure.
references:
  - id: ref_1
    name: Reference 1
    description: Located in the bottol left corner.
    pos:
        x: 24
        y: 33
        z: 0
  - id: ref_2
    name: Reference 2
    description: Located near the bottom right corner.
    pos:
        x: 86
        y: 42
        z: 0
sockets:
  - id: socket_1
    name: Socket 1
    pos:
        x: 69
        y: 34
        z: 0
  - id: socket_2
    name: Socket 2
    pos:
        x: 69
        y: 44
        z: 0
  - id: socket_3
    name: Socket 3
    pos:
        x: 72
        y: 34
        z: 0
  - id: socket_4
    name: Socket 4
    pos:
        x: 72
        y: 49
        z: 0
