id: default_hme_s
name: Default HME S
description: Default wafer, east half-moon, southern structure.
connections:
  - id: flute_1
    name: Flute 1
    pos:
        x: 69
        y: 34
        z: 0
  - id: flute_2
    name: Flute 2
    pos:
        x: 69
        y: 44
        z: 0
  - id: flute_3
    name: Flute 3
    pos:
        x: 72
        y: 34
        z: 0
  - id: flute_4
    name: Flute 4
    pos:
        x: 72
        y: 49
        z: 0
