id: default
name: Default
description: Default PQC measurement sequence.
contacts:
  - name: PQC Flute 1
    contact_id: flute_1
    measurements:
      - name: Polysilicon Van-der-Pauw cross
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D11, 2E09, 2F10, 2G12]
            current_start: -10 uA
            current_stop: 10 uA
            current_step: 500 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_accept_compliance: true
            vsrc_sense_mode: remote
            analysis_functions:
              - type: iv
                limits:
                  i_800: {minimum: 0.25, maximum: 22.4}
              - type: van_der_pauw
      - name: Reverse Polysilicon Van-der-Pauw cross
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D12, 2E11, 2F09, 2G10]
            current_start: -10 uA
            current_stop: 10 uA
            current_step: 500 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, van_der_pauw]
      - name: N+ Van-der-Pauw cross
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D11, 2E09, 2F10, 2G12]
            current_start: -1 mA
            current_stop: 1 mA
            current_step: 50 uA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, van_der_pauw]
      - name: Reverse N+ Van-der-Pauw cross
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D12, 2E11, 2F09, 2G10]
            current_start: -1 mA
            current_stop: 1 mA
            current_step: 50 uA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, van_der_pauw]
      - name: P-stop Van-der-Pauw cross
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D11, 2E09, 2F10, 2G12]
            current_start: -500 nA
            current_stop: 500 nA
            current_step: 25 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, van_der_pauw]
      - name: Reverse P-stop Van-der-Pauw cross
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D12, 2E11, 2F09, 2G10]
            current_start: -500 nA
            current_stop: 500 nA
            current_step: 25 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, van_der_pauw]
      - name: FET
        type: iv_ramp_bias_elm
        parameters:
            matrix_channels: [2D11, 2G09, 2A10, 1G02]
            voltage_start: -5 V
            voltage_stop: 10 V
            voltage_step: 0.1 V
            waiting_time: 500 ms
            bias_voltage: 100 mV
            hvsrc_current_compliance: 10 uA
            vsrc_current_compliance: 10 uA
            analysis_functions: [iv, fet]
      - name: MOS capacitor (HV Source)
        type: cv_ramp
        description: Variant using HVSource and LCR
        parameters:
            matrix_channels: [1A01, 1B02, 2H12]
            bias_voltage_start: -5 V
            bias_voltage_stop: 10 V
            bias_voltage_step: 0.1 V
            waiting_time: 100 ms
            hvsrc_current_compliance: 100 uA
            hvsrc_route_terminal: rear
            lcr_frequency: 10 kHz
            lcr_amplitude: 250 mV
            analysis_functions: [cv, mos]
      - name: MOS capacitor (LCR)
        type: cv_ramp_alt
        enabled: false
        description: Variant using only LCR
        parameters:
            matrix_channels: []
            bias_voltage_start: -5 V
            bias_voltage_stop: 10 V
            bias_voltage_step: 0.1 V
            waiting_time: 100 ms
            current_compliance: 1 uA
            sense_mode: local
            route_terminal: rear
            lcr_frequency: 10 kHz
            lcr_amplitude: 250 mV
            analysis_functions: [cv, mos]
      - name: Capacitor test structure (HV Source)
        type: cv_ramp
        description: Variant using HVSource and LCR
        parameters:
            matrix_channels: [1A01, 1B02, 2H12]
            bias_voltage_start: -5 V
            bias_voltage_stop: 5 V
            bias_voltage_step: 0.1 V
            waiting_time: 100 ms
            hvsrc_current_compliance: 100 uA
            hvsrc_sense_mode: local
            hvsrc_route_terminal: rear
            lcr_frequency: 1 kHz
            lcr_amplitude: 250 mV
            analysis_functions: [cv]
      - name: Capacitor test structure (LCR)
        type: cv_ramp_alt
        enabled: false
        description: Variant using only LCR
        parameters:
            matrix_channels: []
            bias_voltage_start: -5 V
            bias_voltage_stop: 5 V
            bias_voltage_step: 0.1 V
            waiting_time: 100 ms
            current_compliance: 100 uA
            sense_mode: local
            route_terminal: rear
            lcr_frequency: 1 kHz
            lcr_amplitude: 250 mV
      - name: Diode IV
        type: iv_ramp_elm
        parameters:
            matrix_channels: [2C11, 2G12, 1A02]
            voltage_start: 0 V
            voltage_stop: -1000 V
            voltage_step: 10 V
            waiting_time: 1 s
            hvsrc_current_compliance: 1 uA
            hvsrc_sense_mode: local
            hvsrc_route_terminal: rear
            hvsrc_filter_enabled: true
            hvsrc_filter_count: 10
            hvsrc_filter_type: repeat
            elm_filter_enabled: false
            elm_filter_count: 10
            elm_filter_type: repeat
            elm_zero_correction: true
            elm_integration_rate: 50
      - name: Diode CV (HV Source)
        type: cv_ramp
        parameters:
            matrix_channels: [1A01, 1B02, 2C11, 2H12]
            bias_voltage_start: 0 V
            bias_voltage_stop: -500 V
            bias_voltage_step: 5 V
            waiting_time: 500 ms
            hvsrc_current_compliance: 100 uA
            hvsrc_sense_mode: local
            hvsrc_route_terminal: rear
            lcr_frequency: 10 kHz
            lcr_amplitude: 250 mV
      - name: Diode CV (V Source)
        type: cv_ramp_vsrc
        description: Alternate diode CV with V Source.
        parameters:
            matrix_channels: []
            bias_voltage_start: 0 V
            bias_voltage_stop: -500 V
            bias_voltage_step: 5 V
            waiting_time: 500 ms
            vsrc_current_compliance: 100 uA
            vsrc_sense_mode: local
            lcr_frequency: 10 kHz
            lcr_amplitude: 250 mV
      - name: Diode CV 10kHz Test
        type: cv_ramp
        enabled: false
        parameters:
            matrix_channels: [1A01, 1B02, 2C11, 2H12]
            bias_voltage_start: 0 V
            bias_voltage_stop: 200 V
            bias_voltage_step: 2.5 V
            waiting_time: 500 ms
            hvsrc_current_compliance: 25 uA
            hvsrc_sense_mode: local
            hvsrc_route_terminal: rear
            lcr_frequency: 10 kHz
            lcr_amplitude: 250 mV
            lcr_integration_time: "long"
            lcr_averaging_rate: 8
      - name: Diode Frequency Scan
        type: frequency_scan
        enabled: false
        parameters:
            matrix_channels: []
            bias_voltage: 300 V
            hvsrc_current_compliance: 10 uA
            hvsrc_sense_mode: local
            hvsrc_route_terminal: rear
            lcr_frequency_start: 100 Hz
            lcr_frequency_stop: 2 MHz
            lcr_frequency_steps: 100
            lcr_amplitude: 250 mV
  - name: PQC Flute 2
    contact_id: flute_2
    measurements:
      - name: GCD
        type: iv_ramp_bias_elm
        parameters:
            matrix_channels: [2D11, 2G09, 2A10, 1G02]
            voltage_start: -10 V
            voltage_stop: 10 V
            voltage_step: 0.1 V
            waiting_time: 500 ms
            bias_voltage: 5 V
            hvsrc_current_compliance: 10 uA
            vsrc_current_compliance: 10 uA
      - name: Polysilicon meander
        type: iv_ramp_elm
        parameters:
            matrix_channels: [2C11, 2G12, 1A02]
            voltage_start: -100 mV
            voltage_stop: 100 mV
            voltage_step: 25 mV
            waiting_time: 200 ms
            hvsrc_current_compliance: 10 uA
            hvsrc_sense_mode: local
            elm_zero_correction: true
            elm_integration_rate: 50
            analysis_functions: [iv, {type: meander, parameters: {w: 5, nsq: 476}}]
      - name: N+ linewidth structure
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D11, 2E09, 2F10, 2G12]
            current_start: -1 mA
            current_stop: 1 mA
            current_step: 50 uA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
      - name: P-stop linewidth structure
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D11, 2E09, 2F10, 2G12]
            current_start: -500 nA
            current_stop: 500 nA
            current_step: 25 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
      - name: Dielectric Breakdown
        type: iv_ramp_elm
        parameters:
            matrix_channels: [2C11, 2G12, 1A02]
            voltage_start: 0 V
            voltage_stop: 250 V
            voltage_step: 10 V
            waiting_time: 500 ms
            hvsrc_current_compliance: 1 uA
            hvsrc_sense_mode: local
            elm_zero_correction: true
            elm_integration_rate: 50
  - name: PQC Flute 3
    contact_id: flute_3
    enabled: false
    measurements:
      - name: Metal meander
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D09, 2E10, 2F11, 2G12]
            current_start: -1 mA
            current_stop: 1 mA
            current_step: 50 uA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, {type: meander, parameters: {w: 10, nsq: 12853}}]
      - name: Metal clover leaf Van-der-Pauw
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D09, 2E10, 2F11, 2G12]
            current_start: -10 mA
            current_stop: 10 mA
            current_step: 500 uA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
      - name: Reverse Metal clover leaf Van-der-Pauw
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D12, 2E09, 2F10, 2G11]
            current_start: -10 mA
            current_stop: 10 mA
            current_step: 500 uA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, van_der_pauw]
      - name: P+ cross-bridge Van-der-Pauw
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D09, 2E10, 2F11, 2G12]
            current_start: -10 uA
            current_stop: 10 uA
            current_step: 500 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, cross]
      - name: Reverse P+ cross-bridge Van-der-Pauw
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D12, 2E09, 2F10, 2G11]
            current_start: -10 uA
            current_stop: 10 uA
            current_step: 500 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, cross]
      - name: Bulk cross
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D09, 2E10, 2F11, 2G12]
            current_start: 0 nA
            current_stop: 500 nA
            current_step: 5 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, cross]
      - name: Diode IV
        type: iv_ramp_elm
        parameters:
            matrix_channels: [1A02, 2C11]
            voltage_start: 0 V
            voltage_stop: -1000 V
            voltage_step: 10 V
            waiting_time: 1 s
            hvsrc_current_compliance: 1 uA
            hvsrc_sense_mode: local
            elm_zero_correction: true
            elm_integration_rate: 50
      - name: Diode CV
        type: cv_ramp
        parameters:
            matrix_channels: [1A01, 1B02, 2H11, 2G12]
            bias_voltage_start: 0 V
            bias_voltage_stop: -500 V
            bias_voltage_step: 5 V
            waiting_time: 500 ms
            hvsrc_current_compliance: 100 uA
            hvsrc_sense_mode: local
            lcr_frequency: 10 kHz
            lcr_amplitude: 250 mV
      - name: Diode Frequency Scan
        type: frequency_scan
        enabled: false
        parameters:
            bias_voltage: 300 V
            current_compliance: 10 uA
            sense_mode: local
            lcr_frequency_start: 100 Hz
            lcr_frequency_stop: 2 MHz
            lcr_frequency_steps: 100
            lcr_amplitude: 250 mV
  - name: PQC Flute 4
    contact_id: flute_4
    enabled: false
    measurements:
      - name: GCD05
        type: iv_ramp_bias_elm
        parameters:
            matrix_channels: [1D02, 2G11, 2A10, 2C12]
            voltage_start: -10 V
            voltage_stop: 10 V
            voltage_step: 0.1 V
            waiting_time: 500 ms
            bias_voltage: 5 V
            hvsrc_current_compliance: 10 uA
            vsrc_current_compliance: 10 uA
            analysis_functions: [iv, gcd]
      - name: N+ CBKR
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D09, 2E10, 2F11, 2G12]
            current_start: -10 uA
            current_stop: 10 uA
            current_step: 100 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, cbkr]
      - name: Polysilicon CBKR
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D09, 2E10, 2F11, 2G12]
            current_start: -10 uA
            current_stop: 10 uA
            current_step: 100 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, cbkr]
      - name: Polysilicon contact chain
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D09, 2E10, 2F11, 2G12]
            current_start: -10 uA
            current_stop: 10 uA
            current_step: 100 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, contact]
      - name: P+ contact chain
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D09, 2E10, 2F11, 2G12]
            current_start: -10 uA
            current_stop: 10 uA
            current_step: 100 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, contact]
      - name: N+ contact chain
        type: iv_ramp_4_wire
        parameters:
            matrix_channels: [2D09, 2E10, 2F11, 2G12]
            current_start: -10 uA
            current_stop: 10 uA
            current_step: 100 nA
            waiting_time: 200 ms
            vsrc_voltage_compliance: 20 V
            vsrc_sense_mode: remote
            analysis_functions: [iv, contact]
