id: default
name: Default
description: Default chuck providing four sample positions.
positions:
  - id: pos_1
    name: Sample 1
    pos:
        x: 100
        y: 250
        z: 0
  - id: pos_2
    name: Sample 2
    pos:
        x: 125
        y: 250
        z: 0
  - id: pos_3
    name: Sample 3
    pos:
        x: 150
        y: 250
        z: 0
  - id: pos_4
    name: Sample 4
    pos:
        x: 175
        y: 250
        z: 0
