id: default
name: Default
description: Default chuck providing four wafer positions.
positions:
  - id: pos_1
    name: Pos 1
    pos:
        x: 100
        y: 250
        z: 0
  - id: pos_2
    name: Pos 2
    pos:
        x: 125
        y: 250
        z: 0
  - id: pos_3
    name: Pos 3
    pos:
        x: 150
        y: 250
        z: 0
  - id: pos_4
    name: Pos 4
    pos:
        x: 175
        y: 250
        z: 0
